const data = {
    products:[
        {
            _id:'1',
            name: 'Burn Mate Iced Tea',
            category: 'Beverages',
            image: '/Product Pictures/BurnMateIcedTea.png',
            price:770,
            countInStock: 10,
            brand: 'Burn' , 
            rating:4.5,
            numReviews:10,
            description: 'Here’s a refreshingly healthy way to lose weight and burn that extra calories. Burn Mate Iced Tea is a drink that you and your body will surely enjoy!',
        },
        {
            _id:'2',
            name: 'Burn Shake',
            category: 'Beverages',
            image: '/Product Pictures/BurnShake.png',
            price:950,
            countInStock: 20,
            brand: 'Burn' , 
            rating:5,
            numReviews:10,
            description: 'Burn Meal Replacement Shake contains high protein which help shake off hunger and other ingredients instrumental in weight loss such as HCA, L-carnitine, Aloe Vera Gel, Green Tea Extract, Green Coffee Bean Extract and Guarana.',
        },
        {
            _id:'3',
            name: 'Liven Alkaline Coffee - Cappuccino',
            category: 'Coffee',
            image: '/Product Pictures/Liven Cappuccino.png',
            price: 320,
            countInStock: 0,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:14,
            description: 'Coffee without Limits! Enjoy your favorite Coffee time with the Deliciously Healthy Liven Coffee. The First Alkaline Coffee with lots of great health benefits made of Premium Arabica Coffee beans.',
        },
        {
            _id:'4',
            name: 'Liven Burn Coffee',
            category: 'Coffee',
            image: '/Product Pictures/LivenBurnCoffee.png',
            price: 420,
            countInStock: 15,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:12,
            description: 'LIVEN BURN COFFEE is made of premium Arabica beans, Satiereal, Carnipure, Green Tea Extract EFLA 942, Garcinia Cambogia and Anhydrous Caffeine. The infusion of these ingredients are formulated to increase metabolism, energy and the feeling of satiety that support weight loss management.',
        },
        {
            _id:'5',
            name: 'Liven Original',
            category: 'Coffee',
            image: '/Product Pictures/LiveOriginal.png',
            price: 320,
            countInStock: 5,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:10,
            description: 'Do you want to enjoy the best of coffee in your cup? Or are you just interested in taking in healthy products? Or you’re coffee addict and always love to take coffee drink without any remorse on quality or quantity? Or you care to try a new thing out? Then consider our sweet healthy alkaline coffee drink.',
        },
        {
            _id:'6',
            name: 'Liven Latte',
            category: 'Coffee',
            image: '/Product Pictures/LivenLatte.png',
            price: 320,
            countInStock: 12,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:15,
            description: 'Liven Alkaline Coffee is high quality and highly regarded for its distinct taste and aroma because it is made of the finest class of Arabica Coffee beans, and fortified with the COMPLETE PHYTO- ENERGIZER!',
        },
    ],
};
export default data;